### ISSUE TITLE
Can you please create a new release with scoverage disabled

### ISSUE THREAD

**Issue by smashtup** [algolia/algoliasearch-client-scala#391]
Latest release has: "coverageEnabled := true"

I suspect this is causing something to be left behind in the latest release as I'm getting the following error when trying to use the client library:

Caused by: java.io.FileNotFoundException: /Users/rcschermesser/Projects/algoliasearch-client-scala/target/scala-2.11/scoverage-data/scoverage.measurements.147 (No such file or directory)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileWriter.<init>(FileWriter.java:107)
	at scoverage.Invoker$$anonfun$1.apply(Invoker.scala:42)
	at scoverage.Invoker$$anonfun$1.apply(Invoker.scala:42)
	at scala.collection.concurrent.TrieMap.getOrElseUpdate(TrieMap.scala:901)
	at scoverage.Invoker$.invoked(Invoker.scala:42)
	at algolia.AlgoliaClientConfiguration$.<init>(AlgoliaClientConfiguration.scala:37)
	at algolia.AlgoliaClientConfiguration$.<clinit>(AlgoliaClientConfiguration.scala)

**Comment by ElPicador** [comment]
Thanks for the report.
I've also discovered it yesterday.

I'll release a `1.23.1` ASAP

**Comment by ElPicador** [comment]
Version `1.23.2` released with the fix!

**Comment by smashtup** [comment]
Cheers. Thanks for the quick turnaround
